spring:

  flyway:
    enabled: true

  h2:
    console:
      enable: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

  datasource:
    platform: h2
    url: jdbc:h2:file:~/cashiers;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE";
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: never
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
